### ISSUE TITLE
/island create not working no matter what I do

### ISSUE THREAD

**Issue by Perkaholics** [SavageLabs/SavageSkyblock-OLD#24]
This is what happens when I try to do /island create:

org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin SavageSkyblock v2.0.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1606) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-561]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_72]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-561]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-561]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at net.prosavage.savageskyblock.Island.loadSchematic(Island.java:417) ~[?:?]
	at net.prosavage.savageskyblock.Island.<init>(Island.java:98) ~[?:?]
	at net.prosavage.savageskyblock.IslandManager.createIsland(IslandManager.java:63) ~[?:?]
	at net.prosavage.savageskyblock.Command.onCommand(Command.java:405) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-561]
	... 15 more

I tried everything but you said you fixed this in an earlier version of the plugin but I couldn't seem to get around it. I tried with other plugins and I tired it by its self in hopes of isolating the problem but still no luck. Thanks for the help!

**Comment by PeachesMLG** [comment]
fixed
